/* ============================================
   SPECIES — le catalogue des espèces
   ============================================
   Ici : uniquement des DONNÉES. Aucune logique. Ajouter un animal au site,
   c'est ajouter une entrée ici (+ son .glb dans models/). Rien d'autre à toucher.

   Champs (voir DESIGN.md §4) :
     rarete       'commun' | 'peu-commun' | 'rare' | 'legendaire'   (étape 4)
     heures       phases de la journée où l'espèce sort               (étape 4)
     taille       longueur en mètres, pour la fiche et les marges de trajectoire
     vitesse      m/s de croisière ; l'animation « swim » est calée dessus
     profondeur   [yMin, yMax] plage de hauteur où il nage (le sol est à -3, l'œil à 1,6)
     distance     [zProche, zLoin] plage de distance à la vitre (négatif = devant nous)
     ondulation   amplitude (m) des écarts de la trajectoire : 0 = ligne droite
     groupe       nombre d'individus par passage
     echelle      correctif si le .glb n'est pas à l'échelle (1 = déjà en mètres)
   ============================================ */

export const ESPECES = [
  {
    id: 'requin-recif',
    nom: 'Requin gris de récif',
    latin: 'Carcharhinus amblyrhynchos',
    rarete: 'peu-commun',
    heures: ['aube', 'jour', 'crepuscule', 'nuit'],
    taille: 1.8,
    vitesse: 1.3,
    profondeur: [-1.2, 2.4],
    distance: [-4, -13],
    ondulation: 0.6,
    groupe: 1,
    modele: 'models/requin-recif.glb',
    image: 'models/requin-recif.png',
    echelle: 1,
    description: "Élégant et nerveux, le requin gris de récif patrouille les tombants coralliens en petits groupes. Il dépasse rarement deux mètres et se reconnaît à la large bordure sombre de sa nageoire caudale. Curieux, il s'approche des plongeurs, puis s'éloigne d'un coup de queue.",
    habitat: "Récifs et tombants de l'Indo-Pacifique, de la mer Rouge à la Polynésie",
    anecdote: "Menacé, il adopte une posture d'intimidation célèbre : dos arqué, pectorales abaissées, nage en zigzag exagéré.",
  },
  {
    id: 'chirurgien',
    nom: 'Poisson-chirurgien bleu',
    latin: 'Paracanthurus hepatus',
    rarete: 'commun',
    heures: ['aube', 'jour'],
    taille: 0.3,
    vitesse: 0.45,
    profondeur: [-0.6, 2.0],
    distance: [-2.5, -6],
    ondulation: 0.5,
    groupe: 4,
    modele: 'models/chirurgien.glb',
    image: 'models/chirurgien.png',
    echelle: 1,
    description: "Bleu électrique barré d'une « palette » noire, la queue jaune vif : impossible de le confondre. Il vit en petits groupes dans les récifs, toujours près d'une anfractuosité où se cacher. Herbivore, il broute les algues des coraux du matin au soir.",
    habitat: "Récifs coralliens de l'Indo-Pacifique, entre 2 et 40 m",
    anecdote: "Le « scalpel » qui lui vaut son nom est une lame rétractable de chaque côté de la queue, qu'il dresse quand on l'importune.",
  },
  {
    id: 'requin-marteau',
    nom: 'Requin-marteau halicorne',
    latin: 'Sphyrna lewini',
    rarete: 'rare',
    heures: ['crepuscule', 'nuit'],
    taille: 3.2,
    vitesse: 1.1,
    profondeur: [-1.0, 2.6],
    distance: [-6, -14],
    ondulation: 0.8,
    groupe: 1,
    modele: 'models/requin-marteau.glb',
    image: 'models/requin-marteau.png',
    echelle: 1,
    description: "Sa tête aplatie en T lui donne un champ de vision presque total et une sensibilité électrique hors norme, qu'il balaie sur le sable pour débusquer les raies enfouies. Le jour, il se rassemble parfois par centaines autour des monts sous-marins ; c'est la nuit qu'il chasse, seul.",
    habitat: "Eaux tempérées et tropicales du globe, du littoral jusqu'à 275 m de profondeur",
    anecdote: "Ses bancs de plusieurs centaines d'individus, aux Galápagos ou à l'île Cocos, restent l'un des grands mystères du comportement des requins.",
  },
  {
    id: 'tortue',
    nom: 'Tortue verte',
    latin: 'Chelonia mydas',
    rarete: 'peu-commun',
    heures: ['aube', 'jour', 'crepuscule'],
    taille: 1.2,
    vitesse: 0.45,
    profondeur: [-1.2, 2.2],
    distance: [-3.5, -10],
    ondulation: 0.7,
    groupe: 1,
    modele: 'models/tortue.glb',
    image: 'models/tortue.png',
    echelle: 1,
    description: "Lente et paisible, la tortue verte doit son nom à la couleur de sa graisse, pas à sa carapace. Elle broute les herbiers et peut rester plus de quatre heures sous l'eau au repos. Adulte, elle n'a plus grand-chose à craindre — sauf les filets, et les sacs plastique qu'elle confond avec des méduses.",
    habitat: "Eaux tropicales et subtropicales, herbiers et récifs peu profonds",
    anecdote: "Elle revient pondre sur la plage même où elle est née, parfois à des milliers de kilomètres, guidée par le champ magnétique terrestre.",
  },
  {
    id: 'meduse',
    nom: 'Méduse lune',
    latin: 'Aurelia aurita',
    rarete: 'peu-commun',
    heures: ['aube', 'jour', 'crepuscule', 'nuit'],
    taille: 0.4,
    vitesse: 0.18,
    profondeur: [0.3, 4.0],
    distance: [-2.5, -7],
    ondulation: 1.2,
    groupe: 2,
    emission: 0x86c5ee,                    // elle luit la nuit (voir animal.js)
    modele: 'models/meduse.glb',
    image: 'models/meduse.png',
    echelle: 1,
    description: "Un disque translucide de la taille d'une assiette, quatre anneaux rosés qui transparaissent : ses gonades. Elle ne nage pas vraiment, elle pulse — et se laisse porter par le courant. Sans cerveau ni cœur, elle existe depuis plus de cinq cents millions d'années.",
    habitat: "Toutes les mers tempérées du globe, près des côtes et dans les ports",
    anecdote: "Ses tentacules sont trop courts pour percer la peau humaine : c'est l'une des rares méduses qu'on peut toucher sans dommage.",
  },
  {
    id: 'manta',
    nom: 'Raie manta',
    latin: 'Mobula birostris',
    rarete: 'rare',
    heures: ['aube', 'jour', 'crepuscule'],
    taille: 5,
    vitesse: 0.9,
    profondeur: [-0.5, 3.0],
    distance: [-4, -11],
    ondulation: 0.9,
    groupe: 1,
    modele: 'models/manta.glb',
    image: 'models/manta.png',
    echelle: 1,
    description: "Cinq mètres d'envergure, et pourtant elle vole. Ses deux lobes céphaliques, déroulés, guident le plancton vers sa bouche ; enroulés, ils lui ont valu son ancien nom de « poisson-diable ». Chaque manta porte sur le ventre un motif de taches unique : sa carte d'identité.",
    habitat: "Eaux tropicales et subtropicales, au large et autour des stations de nettoyage des récifs",
    anecdote: "Elle a le plus gros cerveau de tous les poissons, et semble se reconnaître dans un miroir — un test que très peu d'animaux réussissent.",
  },
  {
    id: 'requin-baleine',
    nom: 'Requin-baleine',
    latin: 'Rhincodon typus',
    rarete: 'legendaire',
    heures: ['aube', 'jour', 'crepuscule', 'nuit'],
    taille: 10,
    vitesse: 0.6,
    profondeur: [-0.8, 3.2],
    distance: [-8, -18],
    ondulation: 0.6,
    groupe: 1,
    modele: 'models/requin-baleine.glb',
    image: 'models/requin-baleine.png',
    echelle: 1,
    description: "Le plus grand poisson du monde — dix mètres, parfois plus — et l'un des plus doux : il filtre le plancton, bouche grande ouverte, en nageant à peine plus vite qu'un promeneur. Sa robe à damier de points clairs est unique à chaque individu, comme une empreinte digitale. On ignore encore où il naît, et où il meurt.",
    habitat: "Toutes les mers chaudes du globe, de la surface à plus de mille mètres",
    anecdote: "Pour identifier chaque individu à ses points, les chercheurs utilisent l'algorithme conçu par la NASA pour reconnaître les constellations.",
  },
  {
    id: 'sardine',
    nom: 'Sardine',
    latin: 'Sardina pilchardus',
    rarete: 'commun',
    heures: ['aube', 'jour', 'crepuscule'],
    taille: 0.16,
    vitesse: 0.8,
    profondeur: [-0.5, 2.5],
    distance: [-3, -9],
    ondulation: 0.8,
    groupe: 150,
    banc: true,                            // un seul objet pour tout le groupe (banc.js)
    modele: 'models/sardine.glb',
    image: 'models/sardine.png',
    echelle: 1,
    description: "Seule, elle n'est rien : vingt centimètres d'argent. À des milliers, elle devient une créature unique, qui tourne, se contracte et se déchire sous l'attaque d'un prédateur — le banc réagit plus vite qu'un cerveau. Elle nourrit tout ce qui vit dans l'océan, et une bonne partie de ce qui vit sur terre.",
    habitat: "Eaux côtières de l'Atlantique et de la Méditerranée, entre 25 et 100 m le jour, en surface la nuit",
    anecdote: "Un banc de sardines peut s'étirer sur plusieurs kilomètres et se voir depuis l'espace ; les dauphins, les fous et les requins s'y donnent rendez-vous.",
  },
  {
    id: 'baleine',
    nom: 'Baleine à bosse',
    latin: 'Megaptera novaeangliae',
    rarete: 'legendaire',
    heures: [],                            // jamais tirée au sort : elle ne vient que par un événement
    evenement: true,
    taille: 14,
    vitesse: 0.8,
    profondeur: [-0.5, 2.5],
    distance: [-18, -22],
    ondulation: 0.4,
    groupe: 1,
    modele: 'models/baleine.glb',
    image: 'models/baleine.png',
    echelle: 1,
    description: "Quatorze mètres et trente tonnes, des nageoires longues comme des ailes, et le chant le plus complexe du règne animal : des phrases qui évoluent d'une saison à l'autre et se transmettent d'un océan à l'autre. Elle traverse la moitié du globe chaque année, des eaux polaires où elle mange aux eaux chaudes où elle met bas.",
    habitat: "Tous les océans du monde, en migration",
    anecdote: "Ses chants, enregistrés en 1970, sont partis dans l'espace à bord des sondes Voyager, sur le Disque d'or destiné à d'éventuelles civilisations.",
  },
];
